# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 13:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('ama', '0006_auto_20170428_1235'), ('ama', '0007_auto_20170428_1314')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ama', '0005_auto_20170428_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=9001),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='host',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='votes',
            field=models.IntegerField(default=1),
        ),
    ]
