# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ama', '0006_auto_20170428_1235_squashed_0007_auto_20170428_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=400, null=True),
            preserve_default=False,
        ),
    ]
