# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 07:47
from __future__ import unicode_literals

from django.db import migrations
from ama import utils


def gen_slug(apps, context):
    Post = apps.get_model('ama', 'Post')
    posts = Post.objects.all()
    for post in posts:
        post.slug = utils.get_random_slug()
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ama', '0007_post_slug'),
    ]

    operations = [
        migrations.RunPython(gen_slug, reverse_code=migrations.RunPython.noop),
    ]
