# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ama', '0008_populate_slug_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=400, unique=True),
            preserve_default=False,
        ),
    ]
