# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 15:29
from __future__ import unicode_literals

import ama.utils
import datetime
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ama', '0009_make_slug_unique_again'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='expires_at',
            field=models.DateTimeField(default=ama.utils.get_expiry_delta),
        ),
        migrations.AddField(
            model_name='post',
            name='landing_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='starts_at',
            field=models.DateTimeField(default=timezone.datetime(2017, 5, 2, 15, 29, 50, 545533)),
            preserve_default=False,
        ),
    ]
